version: "3"
services:
  superalgos:
    build: 
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: ghcr.io/superalgos/superalgos:latest
    command: ["minMemo"]
    user: "$UID:$GID"
    ports:
      - '34248:34248'
      - '18041:18041'
    volumes:
      - ./My-Data-Storage:/app/Platform/My-Data-Storage
      - ./My-Log-Files:/app/Platform/My-Log-Files
      - ./My-Workspaces:/app/Platform/My-Workspaces
      - ./My-Network-Nodes-Data:/app/Platform/My-Network-Nodes-Data
      - ./My-Social-Trading-Data:/app/Platform/My-Social-Trading-Data
    restart: on-failure
